name: medication_reminder
description: A Flutter app to remind users to take their meds.

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: 12.0.4
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_timezone:
    git:
      url: https://github.com/tjarvstrand/flutter_timezone.git
      ref: main


  timezone: ^0.9.4
  camera: ^0.10.5+3
  path_provider: ^2.1.1
  path: ^1.8.3
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


